### ISSUE TITLE
[Feature Request] Add support for Podcasts

### ISSUE THREAD

**Issue by xekon** [ampache/ampache-xbmc-plugin#11] opened 2021-02-08 08:04 UTC
[Feature Request] Add support for Podcasts, Currently I can browse my library, artists, albums, playlists, tags, but not podcasts.

`https://ampache.example.com/#browse.php?action=podcast`

I recently started listening to some Tech podcasts, and I love it!

I hope you can add the ability to listen to the podcasts on my Ampache server.

Thank you for this plugin, it has been great using it!

**Comment by lusum** [comment] 2021-02-10 17:30
Podcast support in server don't seems a lot advanced, i mean i cannot add a podcast simply by url, but i have to find a stream url, so i will wait until i will have some working examples in demo server. In reality it is not so difficult, it is simply an url to pass to the player. The problem is the lack of a server to test them.

**Comment by xekon** [comment] 2021-02-10 20:45
In ampache config I enabled podcasts.

```
nano /var/www/ampache/config/ampache.cfg.php
podcast = "true"
```

and here are the two streams I added to my server:

```
https://2.5admins.com/feed/podcast

https://feeds.megaphone.fm/darknetdiaries
```

the 2.5admins one worked without issues, for darknet diaries I had to change some stuff: https://github.com/ampache/ampache/issues/2740

I am not sure if any of this is helpful, I hope it is.

**Comment by lusum** [comment] 2021-02-10 23:04
i have to enable them, so :)

**Comment by xekon** [comment] 2021-02-11 00:17
Yes on my Ampache I can play them via the web interface.

After you add the subscription you have to do a catalog update before the episodes actually download.

I created a new catalog for my podcasts

after subscribing to the streams in the web ui, I then updated the catalog:

The below command is how I did it but you can also use "update" in the catalog admin. Once you do that the episodes should download

`sudo -u www-data php /var/www/ampache/bin/catalog_update.inc -n podcasts -a -g -i`

I set ampache debug to true and log level to 5 because initially the episodes would not download for me, but it was just a linux permissions issue which I resolved.

All of the episodes play for me through the Ampache web interface.

**Comment by lusum** [comment] 2021-02-11 15:30
Impossible to add, i need a playable url, but the api doesn't send one, only the url of the page, the url of the website and a filename. Until the api will be more friendly, i will be difficult.

**Comment by xekon** [comment] 2021-02-12 02:15
Lachlan said the API will support it when Ampache 4.4.0 is released: https://github.com/ampache/ampache/issues/2750

**Comment by lusum** [comment] 2021-02-12 15:29
I think it is possible to add them, i have modified the framework, now it takes a very little support to add them

**Comment by lachlan-00** [comment] 2021-02-16 04:24
https://demo.ampache.dev is running the master branch which is now 4.4.0-develop.

I've been testing with the api4 branch of the python3 lib without issue. (changelog here https://github.com/ampache/ampache/blob/master/docs/CHANGELOG.md )

To make songs and podcast_episodes more similar there's an open issue for adding some of the missing data columns (https://github.com/ampache/ampache/issues/2756)

The missing columns won't go into 4.4.0 but the mime, title and url are all added/corrected in this branch.

**Comment by lusum** [comment] 2021-02-16 11:30
I will start to test.

**Comment by lusum** [comment] 2021-02-16 15:37
Support added, i close this issue

**Closed by lusum** 2021-02-16 15:37 UTC

**Comment by xekon** [comment] 2021-02-16 17:34
Awesome! Thank You Very Much!

**Comment by xekon** [comment] 2021-02-17 03:15
> I think it is possible to add them, i have modified the framework, now it takes a very little support to add them
> 
> Now, if you search them, you can see your podcasts, episodes are disabled waiting for the new interface, so the podcast library view until the server will send the total number.

@lusum Right now in **ampache-xbmc-plugin** I can select "Search..." and find and play my podcast. What do you need added before you can add this to the "Library..." view.

Is there still some info that you need the API to return before it would be possible to add them to the library view?

![2021-02-16_19-14](https://user-images.githubusercontent.com/106644/108151334-4f695400-708b-11eb-9cfa-db39480fd417.png)

**Comment by lusum** [comment] 2021-02-17 08:57
No, it is not a plugin's bug, the server doesn't send podcast total number

**Comment by lachlan-00** [comment] 2021-02-17 09:10
> No, it is not a plugin's bug, the server doesn't send podcast total number

I'll check that for 4.4.0

**Comment by xekon** [comment] 2021-02-18 19:36
@lusum It would now be possible to add podcasts to library view?

@lachlan-00 added the podcast total number https://github.com/ampache/ampache/commit/a4355cc5679845b202051a54f44e1a9cb1fcffee

**Comment by lusum** [comment] 2021-02-19 17:40
It is already present in the 2.0 code.

**Comment by xekon** [comment] 2021-02-19 18:19
Thanks, I just tried it but I am getting an error on both of my systems. I do not know if it is related to the new code so I opened a new issue: https://github.com/ampache/ampache-xbmc-plugin/issues/14

**Comment by xekon** [comment] 2021-02-19 18:50
Just Tested it, works great! Thank You @lusum
